{"text": "2021-01-13T19:55:01.304955+0300 DEBUG hello from debug\n", "record": {"elapsed": {"repr": "0:00:00.029588", "seconds": 0.029588}, "exception": null, "extra": {}, "file": {"name": "run_c.py", "path": "/home/vadim/PycharmProjects/python_beazley/run_c.py"}, "function": "<module>", "level": {"icon": "\ud83d\udc1e", "name": "DEBUG", "no": 10}, "line": 7, "message": "hello from debug", "module": "run_c", "name": "__main__", "process": {"id": 31056, "name": "MainProcess"}, "thread": {"id": 139709761888384, "name": "MainThread"}, "time": {"repr": "2021-01-13 19:55:01.304955+03:00", "timestamp": 1610556901.304955}}}
{"text": "2021-01-13T19:55:01.306021+0300 INFO hello from info\n", "record": {"elapsed": {"repr": "0:00:00.030654", "seconds": 0.030654}, "exception": null, "extra": {}, "file": {"name": "run_c.py", "path": "/home/vadim/PycharmProjects/python_beazley/run_c.py"}, "function": "<module>", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 8, "message": "hello from info", "module": "run_c", "name": "__main__", "process": {"id": 31056, "name": "MainProcess"}, "thread": {"id": 139709761888384, "name": "MainThread"}, "time": {"repr": "2021-01-13 19:55:01.306021+03:00", "timestamp": 1610556901.306021}}}
{"text": "2021-01-13T19:55:01.307533+0300 WARNING hello from warning\n", "record": {"elapsed": {"repr": "0:00:00.032166", "seconds": 0.032166}, "exception": null, "extra": {}, "file": {"name": "run_c.py", "path": "/home/vadim/PycharmProjects/python_beazley/run_c.py"}, "function": "<module>", "level": {"icon": "\u26a0\ufe0f", "name": "WARNING", "no": 30}, "line": 9, "message": "hello from warning", "module": "run_c", "name": "__main__", "process": {"id": 31056, "name": "MainProcess"}, "thread": {"id": 139709761888384, "name": "MainThread"}, "time": {"repr": "2021-01-13 19:55:01.307533+03:00", "timestamp": 1610556901.307533}}}
{"text": "2021-01-13T19:55:01.308832+0300 ERROR hello from error\n", "record": {"elapsed": {"repr": "0:00:00.033465", "seconds": 0.033465}, "exception": null, "extra": {}, "file": {"name": "run_c.py", "path": "/home/vadim/PycharmProjects/python_beazley/run_c.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 10, "message": "hello from error", "module": "run_c", "name": "__main__", "process": {"id": 31056, "name": "MainProcess"}, "thread": {"id": 139709761888384, "name": "MainThread"}, "time": {"repr": "2021-01-13 19:55:01.308832+03:00", "timestamp": 1610556901.308832}}}
{"text": "2021-01-13T19:55:01.309623+0300 CRITICAL hello from critical\n", "record": {"elapsed": {"repr": "0:00:00.034256", "seconds": 0.034256}, "exception": null, "extra": {}, "file": {"name": "run_c.py", "path": "/home/vadim/PycharmProjects/python_beazley/run_c.py"}, "function": "<module>", "level": {"icon": "\u2620\ufe0f", "name": "CRITICAL", "no": 50}, "line": 11, "message": "hello from critical", "module": "run_c", "name": "__main__", "process": {"id": 31056, "name": "MainProcess"}, "thread": {"id": 139709761888384, "name": "MainThread"}, "time": {"repr": "2021-01-13 19:55:01.309623+03:00", "timestamp": 1610556901.309623}}}
{"text": "2021-01-13T19:55:01.310912+0300 ERROR An error has been caught in function '<module>', process 'MainProcess' (31056), thread 'MainThread' (139709761888384):\nTraceback (most recent call last):\n\n> File \"/home/vadim/PycharmProjects/python_beazley/run_c.py\", line 23, in <module>\n    main()\n    \u2514 <function main at 0x7f10b203c040>\n\n  File \"/home/vadim/PycharmProjects/python_beazley/run_c.py\", line 21, in main\n    divide(1, 0)\n    \u2514 <function divide at 0x7f10b6afe1f0>\n\n  File \"/home/vadim/PycharmProjects/python_beazley/run_c.py\", line 17, in divide\n    return a / b\n           \u2502   \u2514 0\n           \u2514 1\n\nZeroDivisionError: division by zero\n", "record": {"elapsed": {"repr": "0:00:00.035545", "seconds": 0.035545}, "exception": {"type": "ZeroDivisionError", "value": "division by zero", "traceback": true}, "extra": {}, "file": {"name": "run_c.py", "path": "/home/vadim/PycharmProjects/python_beazley/run_c.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 23, "message": "An error has been caught in function '<module>', process 'MainProcess' (31056), thread 'MainThread' (139709761888384):", "module": "run_c", "name": "__main__", "process": {"id": 31056, "name": "MainProcess"}, "thread": {"id": 139709761888384, "name": "MainThread"}, "time": {"repr": "2021-01-13 19:55:01.310912+03:00", "timestamp": 1610556901.310912}}}
